Make pipeline green 🦍
Fix tests:

* Skip performance test that gets memory killed in CI
* Skip e2e tests which requires setting up a complete kind cluster, installing multiple charts, etc. in CI
* Fix CRD paths
* Fix nil pointer dereference panics for loggers and recorders
* Adhere to our own validation of CRDs in the tests
* Create client interface for identity provider so we can mock it in tests

Fix helmify by using make file job which includes some manual patching

Remove some unused function parameters

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -33,10 +33,17 @@ assert-controller-gen:
   variables:
     K8S_OP_CONTROLLER_GEN_VERSION: "v0.17.3"
 
+assert-helmify:
+  script:
+  - |
+    set -xeuo pipefail
+    make helm
+    # Diff check
+    if ! git diff --exit-code; then
+      echo "ERROR: found diff after regenerating helmify resources - run the make generate tooling update generated resources."
+      exit 3
+    fi
+
 .helm-base:
   variables:
     HELM_CHART_SOURCE: chart/auth-operator
-
-# TODO: remove once test-cases are fixed and working
-go-test:
-  allow_failure: true
